# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bacia_Hidrografica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Casos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao_iap', models.CharField(max_length=45)),
                ('classificacao_iva', models.CharField(max_length=45)),
                ('risco', models.CharField(max_length=1)),
                ('solucao_sugerida', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Coleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_coleta', models.DateField(verbose_name=b'Data da Coleta')),
            ],
        ),
        migrations.CreateModel(
            name='Coleta_Substancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_coletado', models.FloatField()),
                ('coleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbcapp.Coleta')),
            ],
        ),
        migrations.CreateModel(
            name='Entorno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variavel_entorno', models.CharField(max_length=45)),
                ('cor_hex', models.CharField(max_length=16)),
                ('cor_rgb', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Monitoramento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_monitoramento', models.DateField(verbose_name=b'Data do Monitoramento')),
                ('classificacao_iap', models.CharField(max_length=45, null=True)),
                ('classificacao_iva', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ponto_Monitoramento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('dimensao', models.FloatField()),
                ('bacia_hidrografica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbcapp.Bacia_Hidrografica')),
            ],
        ),
        migrations.CreateModel(
            name='Substancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ponto_monitoramento',
            name='rio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbcapp.Rio'),
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='ponto_monitoramento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbcapp.Ponto_Monitoramento'),
        ),
        migrations.AddField(
            model_name='coleta_substancia',
            name='substancia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbcapp.Substancia'),
        ),
        migrations.AddField(
            model_name='coleta',
            name='ponto_monitoramento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbcapp.Ponto_Monitoramento'),
        ),
        migrations.AddField(
            model_name='coleta',
            name='substancia',
            field=models.ManyToManyField(through='rbcapp.Coleta_Substancia', to='rbcapp.Substancia'),
        ),
        migrations.AddField(
            model_name='casos',
            name='entorno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbcapp.Entorno'),
        ),
    ]
